apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j5rb4r3b8-python
  janus-idp.io/tekton: j5rb4r3b8-python
  backstage.io/kubernetes-id: j5rb4r3b8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5rb4r3b8-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
