apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: j5rb4r3b8-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j5rb4r3b8-python 
  name: j5rb4r3b8-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: j5rb4r3b8-python 
